server:
  port: 9527
spring:
  application:
    name: microservicecloud-zuul-gateway
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true
info: 
  app.name: zjs.bwcx-microservicecloud
  company.name: www.zjs.bwcx.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  
# 路由映射
zuul:
  prefix: /zjs #增加统一的访问前缀
  #此处添加ignored-services的意义是忽略通过服务名可以访问微服务(添加完成之后不能通过服务名访问微服务)
  ignored-services:  "*"
  #ignored-services:  microservicecloud-dept
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**